import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import PDFDocument from "pdfkit";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const report = await prisma.aDRReport.findFirst({
    where: { id, userId: user.id },
    include: {
      medication: true,
      sideEffect: true,
    },
  });

  if (!report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  const content = report.content ? JSON.parse(report.content) : null;

  return new Promise<NextResponse>((resolve) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 40 });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => buffers.push(chunk));
      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(
          new NextResponse(pdfBuffer, {
            headers: {
              "Content-Type": "application/pdf",
              "Content-Disposition": `inline; filename="ADR-Report-${id.slice(-6)}.pdf"`,
            },
          })
        );
      });

      // Header
      doc
        .fontSize(20)
        .fillColor("#0f172a")
        .text("LIFEIFY Consumer ADR Report", { align: "center" })
        .moveDown(0.3);

      doc
        .fontSize(10)
        .fillColor("#64748b")
        .text("Structured Adverse Drug Reaction Summary for Clinical Review", { align: "center" })
        .moveDown(1);

      doc.strokeColor("#cbd5e1").lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke().moveDown(1);

      // Patient Info Section
      doc.fontSize(13).fillColor("#1e293b").text("1. Patient Profile", { underline: true }).moveDown(0.5);
      doc.fontSize(10).fillColor("#334155");
      doc.text(`Name: ${content?.patient?.name ?? user.name ?? "Patient"}`);
      doc.text(`Age / Sex: ${content?.patient?.age ?? "—"} / ${content?.patient?.sex ?? "—"}`);
      doc.text(`Weight: ${content?.patient?.weightKg ? `${content.patient.weightKg} kg` : "—"}`);
      doc.moveDown(1);

      // Suspected Medication Section
      doc.fontSize(13).fillColor("#1e293b").text("2. Suspected Medication", { underline: true }).moveDown(0.5);
      doc.fontSize(10).fillColor("#334155");
      doc.text(`Medication: ${content?.medication?.name ?? report.medication?.name ?? "—"}`);
      doc.text(`Active Ingredient: ${content?.medication?.activeIngredient ?? report.medication?.activeIngredient ?? "—"}`);
      doc.text(`Dosage & Regimen: ${content?.medication?.dose ?? "—"}`);
      doc.text(`Start Date: ${content?.medication?.startDate ?? "—"}`);
      doc.moveDown(1);

      // Adverse Reaction Section
      doc.fontSize(13).fillColor("#1e293b").text("3. Adverse Reaction & Clinical Notes", { underline: true }).moveDown(0.5);
      doc.fontSize(10).fillColor("#334155");
      doc.text(`Reported Symptom: ${content?.reaction?.symptom ?? report.sideEffect?.name ?? "—"}`);
      doc.text(`Severity: ${String(content?.reaction?.severity ?? report.sideEffect?.severity ?? "—").toUpperCase()}`);
      doc.text(`Onset: ${content?.reaction?.onset ?? "—"}`);
      doc.text(`Frequency / Duration: ${content?.reaction?.frequency ?? "—"} / ${content?.reaction?.duration ?? "—"}`);
      doc.text(`Outcome: ${content?.reaction?.outcome ?? "—"}`);
      doc.moveDown(0.5);
      doc.text(`Description / Trigger Context: ${content?.reaction?.description ?? report.sideEffect?.description ?? "None provided"}`);
      doc.moveDown(1.5);

      // Red Flag Assessment
      if (report.sideEffect?.redFlag) {
        doc.fillColor("#b91c1c").fontSize(11).text("IMPORTANT: Clinical Red-Flag Indicators Present. High priority evaluation recommended.", { stroke: false });
        doc.moveDown(1);
      }

      // Disclaimer
      doc.strokeColor("#cbd5e1").lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke().moveDown(0.8);
      doc
        .fontSize(8)
        .fillColor("#94a3b8")
        .text(
          "Notice: This report is generated by LIFEIFY based on patient-logged data and deterministic classification rules. It is designed to assist discussions between patients and certified healthcare providers. It does not constitute an official regulatory pharmacovigilance submission or clinical diagnosis.",
          { align: "justify" }
        );

      doc.end();
    } catch (err) {
      resolve(NextResponse.json({ error: (err as Error).message }, { status: 500 }));
    }
  });
}
