export interface IndianFoodItem {
  id: string;
  name: string;
  nameHi: string;
  category: "breakfast" | "main_course" | "snack" | "dal_curry" | "bread_rice" | "dairy";
  region: "pan_india" | "north" | "south" | "east" | "west";
  servingLabel: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  tags: ("veg" | "nonveg" | "vegan" | "jain" | "gluten_free")[];
  substitutionAlternative?: string;
  substitutionReason?: string;
}

export const INDIAN_FOOD_DATABASE: IndianFoodItem[] = [
  {
    id: "inf-1",
    name: "Roti / Phulka (Whole Wheat)",
    nameHi: "रोटी / फुल्का",
    category: "bread_rice",
    region: "pan_india",
    servingLabel: "1 medium roti (approx 35g dough)",
    servingGrams: 35,
    calories: 85,
    protein: 3.1,
    carbs: 17.5,
    fat: 0.5,
    fiber: 2.8,
    tags: ["veg", "vegan", "jain"],
    substitutionAlternative: "Multigrain / Bajra Roti",
    substitutionReason: "Higher dietary fiber and lower glycemic response.",
  },
  {
    id: "inf-2",
    name: "Yellow Moong Dal Tadka",
    nameHi: "मूंग दाल तड़का",
    category: "dal_curry",
    region: "pan_india",
    servingLabel: "1 medium bowl (150g cooked)",
    servingGrams: 150,
    calories: 140,
    protein: 8.5,
    carbs: 20.0,
    fat: 3.0,
    fiber: 5.2,
    tags: ["veg", "vegan", "jain", "gluten_free"],
    substitutionAlternative: "Sprouted Moong Salad",
    substitutionReason: "More raw micronutrients and enzymatic bioavailability.",
  },
  {
    id: "inf-3",
    name: "Steamed White Rice",
    nameHi: "सफेद चावल",
    category: "bread_rice",
    region: "pan_india",
    servingLabel: "1 cup cooked (150g)",
    servingGrams: 150,
    calories: 195,
    protein: 4.1,
    carbs: 42.5,
    fat: 0.5,
    fiber: 0.8,
    tags: ["veg", "vegan", "jain", "gluten_free"],
    substitutionAlternative: "Steamed Brown Rice or Quinoa",
    substitutionReason: "Preserves the bran layer, offering 3x higher fiber and lower blood sugar spike.",
  },
  {
    id: "inf-4",
    name: "Paneer Tikka (Grilled)",
    nameHi: "पनीर टिक्का",
    category: "main_course",
    region: "north",
    servingLabel: "5 cubes (100g)",
    servingGrams: 100,
    calories: 260,
    protein: 18.0,
    carbs: 6.0,
    fat: 18.5,
    fiber: 1.5,
    tags: ["veg", "gluten_free"],
    substitutionAlternative: "Tofu Tikka",
    substitutionReason: "Lowers saturated fat content by 60% while maintaining protein.",
  },
  {
    id: "inf-5",
    name: "Steamed Idli",
    nameHi: "इडली",
    category: "breakfast",
    region: "south",
    servingLabel: "2 medium idlis (80g)",
    servingGrams: 80,
    calories: 110,
    protein: 4.2,
    carbs: 23.0,
    fat: 0.4,
    fiber: 1.8,
    tags: ["veg", "vegan", "gluten_free"],
    substitutionAlternative: "Oats / Ragi Idli",
    substitutionReason: "Significantly lowers glycemic index with mineral-rich ragi.",
  },
  {
    id: "inf-6",
    name: "South Indian Sambar",
    nameHi: "सांभर",
    category: "dal_curry",
    region: "south",
    servingLabel: "1 large bowl (200g)",
    servingGrams: 200,
    calories: 120,
    protein: 5.5,
    carbs: 18.0,
    fat: 3.2,
    fiber: 4.5,
    tags: ["veg", "vegan", "gluten_free"],
  },
  {
    id: "inf-7",
    name: "Plain Curd / Dahi",
    nameHi: "दही",
    category: "dairy",
    region: "pan_india",
    servingLabel: "1 katori (100g)",
    servingGrams: 100,
    calories: 62,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.2,
    fiber: 0,
    tags: ["veg", "gluten_free"],
    substitutionAlternative: "Low-fat Greek Yogurt",
    substitutionReason: "Doubles protein density while reducing saturated fats.",
  },
  {
    id: "inf-8",
    name: "Rajma Masala",
    nameHi: "राजमा मसाला",
    category: "dal_curry",
    region: "north",
    servingLabel: "1 medium bowl (150g)",
    servingGrams: 150,
    calories: 180,
    protein: 9.0,
    carbs: 26.0,
    fat: 4.5,
    fiber: 7.0,
    tags: ["veg", "vegan", "gluten_free"],
  },
  {
    id: "inf-9",
    name: "Palak Paneer",
    nameHi: "पालक पनीर",
    category: "main_course",
    region: "north",
    servingLabel: "1 bowl (150g)",
    servingGrams: 150,
    calories: 220,
    protein: 11.5,
    carbs: 8.0,
    fat: 16.0,
    fiber: 4.2,
    tags: ["veg", "gluten_free"],
  },
  {
    id: "inf-10",
    name: "Dal Khichdi (Moong + Rice)",
    nameHi: "दाल खिचड़ी",
    category: "main_course",
    region: "pan_india",
    servingLabel: "1 plate (200g)",
    servingGrams: 200,
    calories: 230,
    protein: 7.5,
    carbs: 38.0,
    fat: 5.5,
    fiber: 4.0,
    tags: ["veg", "jain", "gluten_free"],
    substitutionAlternative: "Quinoa / Foxtail Millet Khichdi",
    substitutionReason: "Increases complete amino acids and dietary fiber.",
  },
  {
    id: "inf-11",
    name: "Egg Bhurji (2 Eggs with Onions/Tomatoes)",
    nameHi: "अंडा भुर्जी",
    category: "breakfast",
    region: "pan_india",
    servingLabel: "1 serving (approx 120g)",
    servingGrams: 120,
    calories: 185,
    protein: 14.0,
    carbs: 4.0,
    fat: 12.5,
    fiber: 1.0,
    tags: ["nonveg", "gluten_free"],
    substitutionAlternative: "1 Whole Egg + 3 Egg Whites Bhurji",
    substitutionReason: "Retains high protein while cutting dietary cholesterol and fat.",
  },
  {
    id: "inf-12",
    name: "Poha (Flattened Rice with Peanuts)",
    nameHi: "पोहा",
    category: "breakfast",
    region: "west",
    servingLabel: "1 bowl (120g)",
    servingGrams: 120,
    calories: 210,
    protein: 4.5,
    carbs: 35.0,
    fat: 6.5,
    fiber: 2.5,
    tags: ["veg", "vegan", "gluten_free"],
  },
  {
    id: "inf-13",
    name: "Masala Chai (with Whole Milk & Sugar)",
    nameHi: "मसाला चाय",
    category: "snack",
    region: "pan_india",
    servingLabel: "1 cup (150ml)",
    servingGrams: 150,
    calories: 115,
    protein: 3.0,
    carbs: 16.0,
    fat: 4.5,
    fiber: 0,
    tags: ["veg", "gluten_free"],
    substitutionAlternative: "Ginger Cinnamon Tea without Sugar or Skimmed Milk",
    substitutionReason: "Eliminates 12g refined sugars and halves caloric load.",
  },
];
