import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { audit } from "@/lib/audit";

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const reports = await prisma.aDRReport.findMany({
    where: { userId: user.id },
    include: {
      medication: true,
      sideEffect: true,
    },
    orderBy: { createdAt: "desc" },
  });

  return NextResponse.json({ ok: true, reports });
}

export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const body = await req.json();
    const { sideEffectId } = body;

    if (!sideEffectId) {
      return NextResponse.json({ error: "Side effect ID is required" }, { status: 400 });
    }

    const se = await prisma.sideEffect.findFirst({
      where: { id: sideEffectId, userId: user.id },
      include: { medication: true },
    });

    if (!se) {
      return NextResponse.json({ error: "Side effect not found" }, { status: 404 });
    }

    const profile = await prisma.healthProfile.findUnique({
      where: { userId: user.id },
    });

    const structuredContent = {
      patient: {
        name: user.name ?? "Patient",
        age: profile?.age ?? "Not specified",
        sex: profile?.sex ?? "Not specified",
        weightKg: profile?.weightKg ?? "Not specified",
      },
      medication: {
        name: se.medication?.name ?? "Unspecified",
        dose: se.medication?.dose ? `${se.medication.dose} ${se.medication.doseUnit ?? ""}` : "Not specified",
        activeIngredient: se.medication?.activeIngredient ?? "N/A",
        startDate: se.medication?.startDate ? se.medication.startDate.toISOString().slice(0, 10) : "N/A",
      },
      reaction: {
        symptom: se.name,
        severity: se.severity,
        frequency: se.frequency || "Not specified",
        duration: se.duration || "Not specified",
        onset: se.startedAt ? se.startedAt.toISOString().slice(0, 10) : "N/A",
        description: se.description || "None provided",
        outcome: se.resolved ? "Resolved" : "Ongoing",
      },
      disclaimer: "Structured Consumer Adverse Drug Reaction (ADR) Report generated by LIFEIFY for clinical consultation. Not a regulatory pharmacovigilance submission.",
      generatedAt: new Date().toISOString(),
    };

    const report = await prisma.aDRReport.create({
      data: {
        userId: user.id,
        medicationId: se.medicationId,
        sideEffectId: se.id,
        summary: `ADR Report: ${se.name} (${se.medication?.name ?? "General"})`,
        content: JSON.stringify(structuredContent),
        status: "completed",
      },
    });

    await audit({
      userId: user.id,
      action: "ADR_REPORT_GENERATED",
      entity: "ADRReport",
      entityId: report.id,
    });

    return NextResponse.json({
      ok: true,
      report,
      pdfUrl: `/api/adr-report/${report.id}/pdf`,
    }, { status: 201 });
  } catch (err) {
    return NextResponse.json({ error: (err as Error).message }, { status: 500 });
  }
}
